
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
#    host: 192.168.5.180
    port: 6379
#    password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.5.180:3306/hbh?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/coupon?autoReconnect=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
#  application:
#    name: hhhh
#不需要权限认证模块路径
noCertification: /login@post;/checkPicture@get;/swagger-ui.html@get;/webjars/**@get;/error@get;/swagger-resources/**@get;/swagger-resources@get;/getSite@get;/recycleCouponByCouponIds@get;/logout@get;/couponDown/*@get;/getCouponById@post;/loadStore@post;/admin/login@post;/code/image@get;/admin/valiteCode@post;
#token失效时间（分钟）
token_time: 30
#mybatis设置
mybatis:
  type-aliases-package: com.guardlbt.entity
  mapper-locations: classpath:mapping/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  servlet:
    context-path: /AlipayAwardd
  port: 8080
